language: python

python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install --upgrade pytest-django pytest-pythonpath pytest tox
  - python setup.py install

script:
  - py.test ogmios_tests/test.py
  - pip install tox

env:
  - TOX_ENV=py36-dj111
  - TOX_ENV=py34-dj20
  - TOX_ENV=py36-dj21

script: tox -e $TOX_ENV
