language: python

python:
  - "2.7"
  - "3.4"
  - "nightly"

install:
  - pip install --upgrade pip
  - pip install pytest-django pytest-pythonpath pytest
  - python setup.py install
script:
 - py.test ogmios_tests/test.py
